In [29]:
# Import required libraries
from pathlib import Path
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [30]:
# Define project & Dictionary paths
BASE_DIR = Path(r"C:\Users\Manoj\OneDrive\Desktop\project")
DATA_DIR = BASE_DIR / 'data'

In [31]:
# Load CSV file into DataFrames
customers_data = pd.read_csv(DATA_DIR / 'olist_customers_dataset.csv')
orders_data = pd.read_csv(DATA_DIR / 'olist_orders_dataset.csv')
payments_data = pd.read_csv(DATA_DIR / 'olist_order_payments_dataset.csv')

In [32]:
# Create working copies of DataFrames
customers_df = pd.DataFrame(customers_data)
orders_df = pd.DataFrame(orders_data)
payments_df = pd.DataFrame(payments_data)

In [33]:
# Customers dataset - preview data
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [34]:
# Customers dataset - Check datatype and NULL values
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [35]:
# Customers dataset - Statistical summary
customers_df.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [36]:
# Customers datasert - Check missing values
customers_df.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [37]:
# Customers dataset - Check duplicate values
customers_df.duplicated().sum()

0

In [38]:
# Orders dataset - Preview data
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [39]:
# Orders dataset - Check datatype and Null values
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [40]:
# Orders dataset - Statistical summary
orders_df.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [41]:
# Orders dataset - Check missing values
orders_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [42]:
# Orders dataset - Check duplicate values
orders_df.duplicated().sum()

0

In [43]:
# Convert order date columns to Datetime format
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
orders_df[date_cols] = orders_df[date_cols].apply(lambda cols: pd.to_datetime(cols,errors='coerce'))

In [44]:
# Check missing approved data by order status
orders_df.groupby('order_status')['order_approved_at'].apply(lambda x: x.isna().sum())

order_status
approved         0
canceled       141
created          5
delivered       14
invoiced         0
processing       0
shipped          0
unavailable      0
Name: order_approved_at, dtype: int64

In [45]:
# Fill missing approved Dates for delivered orders
# Using Purchase Timestamp
orders_df.loc[(orders_df['order_approved_at'].isna()) & 
    (orders_df['order_status'] == 'delivered'),'order_approved_at'] = orders_df['order_purchase_timestamp']

In [46]:
# Check missing values carrier delivery dates by order status
orders_df.groupby('order_status')['order_delivered_carrier_date'].apply(lambda x: x.isna().sum())

order_status
approved         2
canceled       550
created          5
delivered        2
invoiced       314
processing     301
shipped          0
unavailable    609
Name: order_delivered_carrier_date, dtype: int64

In [47]:
# Fill missing carrier delivery dates
# Using approved date delivered & shipped orders
mask_carrier = (
    orders_df['order_delivered_carrier_date'].isna() &
    orders_df['order_status'].isin(['delivered','shipped'])
)
orders_df.loc[mask_carrier,'order_delivered_carrier_date'] = orders_df.loc[mask_carrier,'order_approved_at']

In [48]:
# Check using customer delivery dates by orders status
orders_df.groupby('order_status')['order_delivered_customer_date'].apply(lambda x: x.isna().sum())

order_status
approved          2
canceled        619
created           5
delivered         8
invoiced        314
processing      301
shipped        1107
unavailable     609
Name: order_delivered_customer_date, dtype: int64

In [49]:
# Fill missing customer delivery dates 
# Using estimated delivery date for delivered orders
mask_customer = (
    orders_df['order_delivered_customer_date'].isna() &
    (orders_df['order_status'] == 'delivered')
)
orders_df.loc[mask_customer,'order_delivered_customer_date'] = orders_df.loc[mask_customer,'order_estimated_delivery_date']

In [50]:
# Payments dataset - preview data
payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [51]:
# Payments dataset - Check datatypes & Null values
payments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [52]:
# Payments dataset - Statistical summary
payments_df.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [53]:
# Payments dataset - Check duplicates records
payments_df.duplicated().sum()

0

In [54]:
# Payments dataset - Check missing values
payments_df.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [55]:
# Create MySQL connection
con = create_engine('mysql+pymysql://root:12345@localhost/olist_commerce_analytics_db')

# Export cleaned data to MySQL
customers_df.to_sql(
    'olist_customers_data',
    con = con,
    if_exists = 'replace',
    index = False
)

orders_df.to_sql(
    'olist_orders_data',
    con = con,
    if_exists = 'replace',
    index = False
)

payments_df.to_sql(
    'olist_payments_data',
    con = con,
    if_exists = 'replace',
    index = False
)

# Success message
print('Data Successfully Imported✅')

Data Successfully Imported✅

In [56]:
# Export clened data to CSV files
customers_df.to_csv("customers_data.csv",index=False)

orders_df.to_csv("orders_data.csv",index=False)

payments_df.to_csv("payments_data.csv",index=False)

# Success message
print('Data Successfully Imported✅')

Data Successfully Imported✅